# 尾巴关节位置控制器
tail_joint_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
  gains:
    joint1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1.0}
    joint2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1.0}
    joint3: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1.0}
    joint4: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1.0}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
