thruster_manager:
  update_rate: 50
  thruster_topic_prefix: thrusters
  thruster_topic_suffix: input
  thruster_frame_base: thruster
  max_thrusters: 2
  thrusters:
    '0':
      position: [0, 0.1, 0]
      orientation: [0, 0, 0]
      axis: [0, 0, 1]
    '1':
      position: [0, -0.1, 0]
      orientation: [0, 0, 0]
      axis: [0, 0, 1]